export const RESORT_LIST_REQUEST = 'RESORT_LIST_REQUEST'
export const RESORT_LIST_SUCCESS = 'RESORT_LIST_SUCCESS'
export const RESORT_LIST_FAIL = 'RESORT_LIST_FAIL'

export const RESORT_OWNER_LIST_REQUEST = 'RESORT_OWNER_LIST_REQUEST'
export const RESORT_OWNER_LIST_SUCCESS = 'RESORT_OWNER_LIST_SUCCESS'
export const RESORT_OWNER_LIST_FAIL = 'RESORT_OWNER_LIST_FAIL'

export const RESORT_DETAILS_REQUEST = 'RESORT_DETAILS_REQUEST'
export const RESORT_DETAILS_SUCCESS = 'RESORT_DETAILS_SUCCESS'
export const RESORT_DETAILS_FAIL = 'RESORT_DETAILS_FAIL'


export const RESORT_OWNER_DETAILS_REQUEST = 'RESORT_OWNER_DETAILS_REQUEST'
export const RESORT_OWNER_DETAILS_SUCCESS = 'RESORT_OWNER_DETAILS_SUCCESS'
export const RESORT_OWNER_DETAILS_FAIL = 'RESORT_OWNER_DETAILS_FAIL'

export const RESORT_DELETE_REQUEST = 'RESORT_DELETE_REQUEST'
export const RESORT_DELETE_SUCCESS = 'RESORT_DELETE_SUCCESS'
export const RESORT_DELETE_FAIL = 'RESORT_DELETE_FAIL'

export const RESORT_OWNER_DELETE_REQUEST = 'RESORT_OWNER_DELETE_REQUEST'
export const RESORT_OWNER_DELETE_SUCCESS = 'RESORT_OWNER_DELETE_SUCCESS'
export const RESORT_OWNER_DELETE_FAIL = 'RESORT_OWNER_DELETE_FAIL'

export const RESORT_CREATE_REQUEST = 'RESORT_CREATE_REQUEST'
export const RESORT_CREATE_SUCCESS = 'RESORT_CREATE_SUCCESS'
export const RESORT_CREATE_FAIL = 'RESORT_CREATE_FAIL'
export const RESORT_CREATE_RESET = 'RESORT_CREATE_RESET'


export const RESORT_OWNER_CREATE_REQUEST = 'RESORT_OWNER_CREATE_REQUEST'
export const RESORT_OWNER_CREATE_SUCCESS = 'RESORT_OWNER_CREATE_SUCCESS'
export const RESORT_OWNER_CREATE_FAIL = 'RESORT_OWNER_CREATE_FAIL'
export const RESORT_OWNER_CREATE_RESET = 'RESORT_OWNER_CREATE_RESET'


export const RESORT_UPDATE_REQUEST = 'RESORT_UPDATE_REQUEST'
export const RESORT_UPDATE_SUCCESS = 'RESORT_UPDATE_SUCCESS'
export const RESORT_UPDATE_FAIL = 'RESORT_UPDATE_FAIL'
export const RESORT_UPDATE_RESET = 'RESORT_UPDATE_RESET'


export const RESORT_OWNER_UPDATE_REQUEST = 'RESORT_OWNER_UPDATE_REQUEST'
export const RESORT_OWNER_UPDATE_SUCCESS = 'RESORT_OWNER_UPDATE_SUCCESS'
export const RESORT_OWNER_UPDATE_FAIL = 'RESORT_OWNER_UPDATE_FAIL'
export const RESORT_OWNER_UPDATE_RESET = 'RESORT_OWNER_UPDATE_RESET'

export const RESORT_CREATE_REVIEW_REQUEST = 'RESORT_CREATE_REVIEW_REQUEST'
export const RESORT_CREATE_REVIEW_SUCCESS = 'RESORT_CREATE_REVIEW_SUCCESS'
export const RESORT_CREATE_REVIEW_FAIL = 'RESORT_CREATE_REVIEW_FAIL'
export const RESORT_CREATE_REVIEW_RESET = 'RESORT_CREATE_REVIEW_RESET'

export const RESORT_TOP_REQUEST = 'RESORT_TOP_REQUEST'
export const RESORT_TOP_SUCCESS = 'RESORT_TOP_SUCCESS'
export const RESORT_TOP_FAIL = 'RESORT_TOP_FAIL'