export const RESORT_LIST_REQUEST = 'RESORT_LIST_REQUEST'
export const RESORT_LIST_SUCCESS = 'RESORT_LIST_SUCCESS'
export const RESORT_LIST_FAIL = 'RESORT_LIST_FAIL'

export const RESORT_DETAILS_REQUEST = 'RESORT_DETAILS_REQUEST'
export const RESORT_DETAILS_SUCCESS = 'RESORT_DETAILS_SUCCESS'
export const RESORT_DETAILS_FAIL = 'RESORT_DETAILS_FAIL'